stream {
    upstream mqtt_brokers {
        server mqtt_broker1:8081;
        server mqtt_broker2:8082;
    }

    server {
        listen 8080;
        location /mqtt/ {
        proxy_pass http://localhost:1884;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
    }
}

events {}
